services:
  django-web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery:
    build: .
    container_name: celery_worker
    command: celery -A selteq_task worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - django-web
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A selteq_task beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - django-web
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mssql_data:
