# Generated by Django 4.2.20 on 2025-04-09 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_task"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table="tasks_task",
        ),
    ]
